### ISSUE TITLE
Make a v0 release

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/model_seg_generalist#12]
Although the final generalist model is not trained yet, we already have some checkpoints that work nicely. I think we should release a first version of the model in this repo because at the moment its only available on duke. It would thus be easier for the team/users to test the model.

**Comment by ArthurBoschet** [comment]
@hermancollin Do you want my updated model trained with 5 folds with a fixed `splits_final.json`?

**Comment by hermancollin** [comment]
As discussed, we will wait for the next iteration of the model, which will be trained next week.
