### ISSUE TITLE
Wrong custom split filename

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/model_seg_generalist#5]
Wrong filename (should be `splits_final.json` instead). This is problematic and should be further explained. The JSON split file **must be moved** in `nnUNet_preprocessed/DatasetXXX` and overwrite the existing one. I suggest adding an instruction in the README to move the file to the appropriate location or adding a `mv` command in the shell training script.

https://github.com/axondeepseg/model_seg_generalist/blob/e82b2a7448ff02bd670cf3dc2b88833cf3c2f408/nnunet_scripts/aggregate_data.py#L92-L93

**Comment by ArthurBoschet** [comment]
@hermancollin Here is the [PR](https://github.com/axondeepseg/model_seg_generalist/pull/10) addressing this issue.
