### ISSUE TITLE
Study intra-modality aggregation on BF datasets

### ISSUE THREAD

**Issue by hermancollin** [axondeepseg/model_seg_generalist#6]
To study the effect of aggregating data within a single modality, a model will be trained on all 3 BF datasets and compared to the dedicated BF models. We can see this as an "ablation study" for the aggregation process.

Not sure if we should add this pipeline inside this repo or create another one - @ArthurBoschet thoughts on this?

**Comment by ArthurBoschet** [comment]
@hermancollin I think I will just extend the existing aggregation script in this repository to accept additional (optional) arguments that allows us to create generalist models with only a subset of datasets. But let me know what you think!

**Comment by hermancollin** [comment]
Sounds great.

**Comment by ArthurBoschet** [comment]
@hermancollin Here is the [PR](https://github.com/axondeepseg/model_seg_generalist/pull/10) addressing this issue.
